# name: Deploy Rafart-React

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16

#       - name: Install dependencies
#         run: npm ci --legacy-peer-deps

#       - name: Build
#         run: npm run build

#       - name: Deploy Rafart
#         run: npm run export --existing-output-dir=out
#         env:
#           GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Rafart

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"
#       - run: npm ci
#       - run: npm run build
#       - run: npm run export
#       - run: touch ./out/.nojekyll

#       - name: Deploy 🚀
#         uses: rarma4/rafart-react-site
#         with:
#           branch: gh-pages # The branch the action should deploy to.
#           folder: out # The folder the action should deploy.